/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.kidgame;
import javax.swing.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author User
 */
public class MainMenuPanel extends javax.swing.JPanel {
    private JButton btnSinglePlayer;
    private JButton btnExit;
    private KidsMathGameFrame mainFrame;


    public MainMenuPanel(KidsMathGameFrame frame) {
        this.mainFrame = frame;
        initComponents();
    /**
     * Creates new form MainMenuPanel
     */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainmenupanel = new javax.swing.JPanel();
        exitBtton = new javax.swing.JButton();
        singlePlayerButton = new javax.swing.JButton();
        multiPlayerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new javax.swing.OverlayLayout(this));

        exitBtton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        exitBtton.setText("ExiT");
        exitBtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttonActionPerformed(evt);
            }
        });

        singlePlayerButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        singlePlayerButton.setText("SinglePlayer");
        singlePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerButtonActionPerformed(evt);
            }
        });

        multiPlayerButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        multiPlayerButton.setText("Multiplayer");
        multiPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiPlayerButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        jLabel1.setText("MATH LEARNING GAME");

        titleLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jButton1.setText("RESULT");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jProgressBar1.setBackground(new java.awt.Color(51, 0, 102));

        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jButton2.setText("GamePanel");

        javax.swing.GroupLayout mainmenupanelLayout = new javax.swing.GroupLayout(mainmenupanel);
        mainmenupanel.setLayout(mainmenupanelLayout);
        mainmenupanelLayout.setHorizontalGroup(
            mainmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainmenupanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(singlePlayerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multiPlayerButton)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainmenupanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainmenupanelLayout.createSequentialGroup()
                        .addComponent(exitBtton)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainmenupanelLayout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(mainmenupanelLayout.createSequentialGroup()
                .addGroup(mainmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainmenupanelLayout.createSequentialGroup()
                        .addGap(904, 904, 904)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainmenupanelLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1))
                    .addGroup(mainmenupanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainmenupanelLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainmenupanelLayout.setVerticalGroup(
            mainmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenupanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(mainmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiPlayerButton)
                    .addComponent(singlePlayerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(105, 105, 105)
                .addComponent(exitBtton)
                .addGap(60, 60, 60))
        );

        add(mainmenupanel);
    }// </editor-fold>//GEN-END:initComponents

    private void singlePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerButtonActionPerformed
        SinglePlayerSetupPanel sp = new SinglePlayerSetupPanel();  // TODO add your handling code here:
        this.getParent().removeAll();
        this.getParent().add(sp);
        this.getParent().revalidate();
        this.getParent().repaint();
    }//GEN-LAST:event_singlePlayerButtonActionPerformed

    private void multiPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiPlayerButtonActionPerformed
         MultiPlayerSetupPanel mp = new MultiPlayerSetupPanel();
        this.getParent().removeAll();
        this.getParent().add(mp);
        this.getParent().revalidate();
        this.getParent().repaint();// TODO add your handling code here:
    }//GEN-LAST:event_multiPlayerButtonActionPerformed

    private void exitBttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttonActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitBttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainmenupanel;
    private javax.swing.JButton multiPlayerButton;
    private javax.swing.JButton singlePlayerButton;
    private javax.swing.JPanel titleLabel;
    // End of variables declaration//GEN-END:variables
}
